package ds.hk.lang;

/**			Hash Code	<br/><br/>
 * 
 * Every Object has its own hash-code generated by JVM,		<br/>
 * Even Superclass has separate hash-code		<br/><br/>
 * 
 * This class retrieves JVM given hash-code using System.identityHashCode(<ClassName>.class)
 */

public class HashCode extends A {

	HashCode(String name, int num) {
		super(name, num);
	}

	public static void main(String[] args) {
		
		new HashCode ("Hapheej", 33).retrieveHashCode();
	}
	
	void retrieveHashCode() {

		System.out.println("JVM hashCode for A class: " + System.identityHashCode(A.class));
		
		//Super Class And Sub Class Always Has Same Hash Code
		System.out.println("hashCode() for A class: "+ super.hashCode());
		System.out.println("hashCode() for Subclass/HashCode class: "+ this.hashCode());
		
		System.out.println("JVM hashCode for Super/Object class: "+ this.JVMHashCodeForA());
		Object obj = (Object) this;
		System.out.println("JVM hashCode for Object class: " + System.identityHashCode(obj));
		
		//Has Code from Overridden method hashCode(obj)
		System.out.println(obj.hashCode());
	}
}
